### ISSUE TITLE
Create an ER Diagram for the database

### ISSUE THREAD

**Issue by Rosshill98** [TaskHatch/taskhatch#10]

**Comment by Rosshill98** [comment]
Cam did this

**Comment by Rosshill98** [comment]
cam is still doing this

**Comment by rsgc-raymond-c** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/14296589/11661524/5503238c-9da0-11e5-84e9-9b9005812517.jpg)

**Comment by rsgc-raymond-c** [comment]
Updated

![fullsizerender](https://cloud.githubusercontent.com/assets/14296589/11661989/9ae0b872-9da2-11e5-8220-2539c21338f7.jpg)

**Comment by rgordonatrsgc** [comment]
This issue requires an assignee and a milestone.
