### ISSUE TITLE
Create Database Tables

### ISSUE THREAD

**Issue by rsgc-raymond-c** [TaskHatch/taskhatch#11]

**Comment by rsgc-raymond-c** [comment]
![fullsizerender 01](https://cloud.githubusercontent.com/assets/14296589/11661991/a21a1296-9da2-11e5-8070-97ae7d73f97e.jpg)

**Comment by rgordonatrsgc** [comment]
This issue should have both a milestone and a label. Suggestion: sprint1 and 'design'
