### ISSUE TITLE
Finish database model with MySQL workbench

### ISSUE THREAD

**Issue by Rosshill98** [TaskHatch/taskhatch#12]

**Comment by rgordonatrsgc** [comment]
Please assign this to a milestone.

**Comment by Rosshill98** [comment]
Cam is working on this

**Comment by rsgc-raymond-c** [comment]
![screen shot 2015-12-14 at 11 43 38 am](https://cloud.githubusercontent.com/assets/14296589/11787080/f300e36a-a257-11e5-997a-75fad6e62788.png)
