### ISSUE TITLE
Do more user testing with paper prototypes

### ISSUE THREAD

**Issue by Rosshill98** [TaskHatch/taskhatch#15]

**Comment by rsgc-linsdell-j** [comment]
https://www.youtube.com/watch?v=UeKugekav3M

**Comment by rsgc-linsdell-j** [comment]
https://www.youtube.com/watch?v=9w8nNp22krQ

**Comment by rgordonatrsgc** [comment]
Who was your test subject for this prototyping session? What was the feedback given? Please watch the video, and add summary of observations / feedback given to this issue. Add any changes to the Wiki.

**Comment by rsgc-linsdell-j** [comment]
Made changes to the wiki based on the minimal feedback we received. Participants were pushed to give any feedback they could think of, but non was given.
