### ISSUE TITLE
Expand user.html

### ISSUE THREAD

**Issue by Rosshill98** [TaskHatch/taskhatch#17]
Bio, shared projects, latest activity, etc.

**Comment by rsgc-linsdell-j** [comment]
minor change ef5e1c9fcd4d949294851a1187ff5cee3d9b1cb1

**Comment by rgordonatrsgc** [comment]
What are the parameters of this issue? If the intent is to implement the "user" page, suggest that you post the paper-prototype snapshot of that page to this issue, so the assignee (and the scrum master, ie. me) knows what is being worked on.  See example of what I'm referring to in [issue 12](https://github.com/rsgc-ics4u-2015/curriculum-organizer/issues/12) of the Curriculum Organizer exemplar.

**Comment by rsgc-linsdell-j** [comment]
![12544692_727476624018983_218648140_o](https://cloud.githubusercontent.com/assets/14296620/12379524/d35e86be-bd2a-11e5-8cc7-877066897fea.jpg)
Trying to emulate this photo. We had many designs for the page, which is why it took so many iterations to complete.
