### ISSUE TITLE
Update CSS for Index.html

### ISSUE THREAD

**Issue by rsgc-raymond-c** [TaskHatch/taskhatch#18]

**Comment by rsgc-raymond-c** [comment]
e420a4cc9803ce9ec6b8f1d05aba7b33f8e78112

**Comment by rgordonatrsgc** [comment]
For issues, please be sure to clearly describe the intent. Also, inspecting the changeling on that commit, it doesn't seem like very much was done for the change – added 3 lines to the CSS file and some document text for the index.html page. Did this really even need a separate issue?
