### ISSUE TITLE
Create project page mockup

### ISSUE THREAD

**Issue by Rosshill98** [TaskHatch/taskhatch#6]

**Comment by rsgc-linsdell-j** [comment]
Done ross will add image since i dont have a phone right now.

**Comment by rsgc-linsdell-j** [comment]
![12305959_660569387413873_751609370_n](https://cloud.githubusercontent.com/assets/14296620/11478717/9b502b0e-975c-11e5-9c63-5d5bc8483f39.jpg)

**Comment by rgordonatrsgc** [comment]
Please assign a milestone.
