### ISSUE TITLE
Finish CSS for all templates

### ISSUE THREAD

**Issue by Rosshill98** [TaskHatch/taskhatch#8]

**Comment by Rosshill98** [comment]
- [x] linked up CSS with HTML templates (a3f209f)
- [x] Completed CSS for index (271112f)
- [ ] Completed CSS for teams
- [ ] Completed CSS for users
- [ ] Completed CSS for projects
- [ ] Completed standard CSS

**Comment by Rosshill98** [comment]
Closed task 1 with a3f209f
Closed task 2 with 271112f

**Comment by Rosshill98** [comment]
Completed task 3 with becaf44

**Comment by Rosshill98** [comment]
Closed task 4 with d429b80

**Comment by rsgc-linsdell-j** [comment]
Started User Html/CSS. Here is the commit that involved this code b9e8c80ea02bcebb4748c5ab0c0f220083d84506

**Comment by rsgc-linsdell-j** [comment]
Finished HTML/CSS for users with 556404a03661c6f27bd52675c8609e1bed6a46ce

**Comment by Rosshill98** [comment]
All tasks completed!

**Comment by rgordonatrsgc** [comment]
Hi Ross – please assign a milestone to this issue.
