### ISSUE TITLE
Create paper protoypes for user testing

### ISSUE THREAD

**Issue by Rosshill98** [TaskHatch/taskhatch#9]

**Comment by rsgc-linsdell-j** [comment]
Created many different pages to be used for paper prototyping the site. Used students in class to run through the pages, and when missing functions were discovered I went back and fixed them. This process was repeated multiple times. Now that I have all of the sheets required, I will create a formal prototyping video next class.

**Comment by rsgc-linsdell-j** [comment]
https://www.youtube.com/watch?v=GOcqJ2JBnno&feature=youtu.be

here is a youtube video of our finalized paper prototyping run-through.

**Comment by rgordonatrsgc** [comment]
What was the feedback received through the prototyping process? How did that change features to be implemented?  All of this should be described on your [Wiki](https://github.com/TaskHatch/taskhatch/wiki) which is presently incomplete. You can use the [House Points Wiki](https://github.com/rsgc-ics4u-2015/house-points/wiki) as a model.

**Comment by rgordonatrsgc** [comment]
This issue also requires a milestone.

**Comment by rgordonatrsgc** [comment]
The video for your paper prototyping session did not seem to contain any audio. I've noted that the wiki was never revised based on feedback given, per my comment from Dec 14.
